In [1]:
import duckdb

# import ehrapy as ep
import ehrdata
import pandas as pd
import os

In [30]:
con = duckdb.connect()
ehrdata.dt.mimic_iv_omop(backend_handle=con)
# obs.head()

Path to data exists, load tables from there: ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9
missing tables:  [['concept'], ['vocabulary'], ['domain'], ['concept_class'], ['concept_relationship'], ['relationship'], ['concept_synonym'], ['concept_ancestor'], ['source_to_concept_map'], ['drug_strength']]

In [20]:
obs.head()

,person_id,gender_concept_id,year_of_birth,month_of_birth,day_of_birth,birth_datetime,race_concept_id,ethnicity_concept_id,location_id,provider_id,care_site_id,person_source_value,gender_source_value,gender_source_concept_id,race_source_value,race_source_concept_id,ethnicity_source_value,ethnicity_source_concept_id
0,3589912774911670296,8507,2095,None,None,None,0,38003563,None,None,None,10009628,M,0,None,0,HISPANIC/LATINO,2000001408
1,-3210373572193940939,8507,2079,None,None,None,0,38003563,None,None,None,10011398,M,0,None,0,HISPANIC/LATINO,2000001408
2,-775517641933593374,8507,2149,None,None,None,8516,0,None,None,None,10004235,M,0,BLACK/AFRICAN AMERICAN,2000001406,None,0
3,-2575767131279873665,8507,2050,None,None,None,8516,0,None,None,None,10024043,M,0,BLACK/AFRICAN AMERICAN,2000001406,None,0
4,-8970844422700220177,8507,2114,None,None,None,8527,0,None,None,None,10038933,M,0,WHITE,2000001404,None,0

In [6]:
obs2 = ehrdata.io.omop.extract_observation_period(con)
obs2.head()

,person_id,gender_concept_id,year_of_birth,month_of_birth,day_of_birth,birth_datetime,race_concept_id,ethnicity_concept_id,location_id,provider_id,...,gender_source_value,gender_source_concept_id,race_source_value,race_source_concept_id,ethnicity_source_value,ethnicity_source_concept_id,observation_period_id,observation_period_start_date,observation_period_end_date,period_type_concept_id
0,-3210373572193940939,8507,2079,None,None,None,0,38003563,None,None,...,M,0,None,0,HISPANIC/LATINO,2000001408,2193156378042005101,2146-05-28,2147-03-26,32828
1,-775517641933593374,8507,2149,None,None,None,8516,0,None,None,...,M,0,BLACK/AFRICAN AMERICAN,2000001406,None,0,8196716582395037703,2196-02-24,2196-06-22,32828
2,-2575767131279873665,8507,2050,None,None,None,8516,0,None,None,...,M,0,BLACK/AFRICAN AMERICAN,2000001406,None,0,-4712462436630318946,2116-06-25,2117-06-09,32828
3,-8970844422700220177,8507,2114,None,None,None,8527,0,None,None,...,M,0,WHITE,2000001404,None,0,-9178218221840740161,2148-09-10,2148-09-23,32828
4,4668337230155062633,8507,2073,None,None,None,8527,0,None,None,...,M,0,WHITE,2000001404,None,0,4438236770478758867,2116-12-02,2117-12-06,32828

In [ ]:
ep.dt.testload(mimic)

In [29]:
path_dir = "/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv"
csv_files = []
for file in sorted(os.listdir(path_dir)):
    if file.endswith("csv"):
        load_path = os.path.join(path_dir, file)
        csv_files.append(load_path)
        df_temp = pd.read_csv(load_path, header=None)
        print(f"The shape of {file} is {df_temp.shape}")

The shape of 2b_concept.csv is (3886, 10)
The shape of 2b_concept_relationship.csv is (7717, 6)
The shape of 2b_vocabulary.csv is (28, 5)
The shape of attribute_definition.csv is (1, 5)
The shape of care_site.csv is (32, 6)
The shape of cdm_source.csv is (2, 10)
The shape of cohort.csv is (1, 4)
The shape of cohort_attribute.csv is (1, 7)
The shape of cohort_definition.csv is (1, 7)
The shape of condition_era.csv is (3772, 6)
The shape of condition_occurrence.csv is (16442, 16)
The shape of cost.csv is (1, 22)
The shape of death.csv is (16, 7)
The shape of device_exposure.csv is (3856, 15)
The shape of dose_era.csv is (118, 7)
The shape of drug_era.csv is (7932, 7)
The shape of drug_exposure.csv is (18230, 23)
The shape of fact_relationship.csv is (1753, 5)
The shape of location.csv is (2, 8)
The shape of measurement.csv is (338551, 20)
The shape of metadata.csv is (1, 7)
The shape of note.csv is (1, 14)
The shape of note_nlp.csv is (1, 14)
The shape of observation.csv is (31391, 18)
The shape of observation_period.csv is (101, 5)
The shape of payer_plan_period.csv is (1, 17)
The shape of person.csv is (101, 18)
The shape of procedure_occurrence.csv is (18448, 14)
The shape of provider.csv is (1, 13)
The shape of specimen.csv is (151, 15)
The shape of visit_detail.csv is (14480, 19)
The shape of visit_occurrence.csv is (853, 17)

/var/folders/hz/87xlh4vx2l56g7gpljc_45l00000gn/T/ipykernel_7177/798556094.py:7: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(load_path, header=None)

In [4]:
csv_files

['/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/provider.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/2b_vocabulary.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/observation_period.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/drug_exposure.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/care_site.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/2b_concept.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/cohort_definition.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/cost.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/specimen.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/death.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/device_exposure.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/attribute_definition.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/fact_relationship.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/dose_era.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/location.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/measurement.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/cohort.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/note_nlp.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/cohort_attribute.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/condition_occurrence.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/2b_concept_relationship.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/drug_era.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/cdm_source.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/visit_occurrence.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/metadata.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/person.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/observation.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/visit_detail.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/payer_plan_period.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/procedure_occurrence.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/note.csv',
 '/Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/condition_era.csv']

In [5]:
dfs_to_merge = []

for file in csv_files:
    # Load the CSV file
    df_temp = pd.read_csv(os.path.join(path_dir, file))
    if "person_id" in df_temp.columns:
        print(f"Adding {file} to list")
        dfs_to_merge.append(df_temp[:10])

# Merge all DataFrames on 'person_id'
merged_df = obs  # Start with person_df

for df in dfs_to_merge:
    merged_df = pd.merge(merged_df, df, on="person_id", how="left")

Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/observation_period.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/drug_exposure.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/specimen.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/death.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/device_exposure.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/dose_era.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/measurement.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/condition_occurrence.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/drug_era.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/visit_occurrence.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/person.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/observation.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/visit_detail.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/payer_plan_period.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/procedure_occurrence.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/note.csv to list
Adding /Users/shrey.parikh/Desktop/EHR/ehrdata/docs/notebooks/ehrapy_data/mimic-iv-demo-data-in-the-omop-common-data-model-0.9/1_omop_data_csv/condition_era.csv to list

/var/folders/hz/87xlh4vx2l56g7gpljc_45l00000gn/T/ipykernel_7177/1927311707.py:5: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(os.path.join(path_dir, file))

In [8]:
for df in dfs_to_merge:
    merged_df = pd.merge(merged_df, df, on="person_id", how="left", suffixes=("", "_dup"))

In [18]:
cols_to_drop = merged_df.columns[merged_df.columns.str.contains("dup")].tolist()

In [22]:
merged_df_filt = merged_df.drop(cols_to_drop, axis=1)

In [26]:
len(merged_df_filt.person_id.unique())

100

In [27]:
merged_df_filt

,person_id,gender_concept_id,year_of_birth,month_of_birth,day_of_birth,birth_datetime,race_concept_id,ethnicity_concept_id,location_id,provider_id_x,...,note_class_concept_id,note_title,note_text,encoding_concept_id,language_concept_id,note_source_value,condition_era_id,condition_era_start_date,condition_era_end_date,condition_occurrence_count
0,3589912774911670296,8507,2095,None,None,None,0,38003563,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-3210373572193940939,8507,2079,None,None,None,0,38003563,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-775517641933593374,8507,2149,None,None,None,8516,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-2575767131279873665,8507,2050,None,None,None,8516,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-8970844422700220177,8507,2114,None,None,None,8527,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5396,-7671795861352464589,8532,2052,None,None,None,2000001401,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5397,5734523979606454056,8532,2069,None,None,None,2000001401,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5398,1532249960797525190,8532,2106,None,None,None,2000001405,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5399,5894416985828315484,8532,2055,None,None,None,2000001405,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5400,-3780452582396805474,8532,2058,None,None,None,2000001405,0,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN